FROM php:7.4-fpm

# Cài đặt các extension cần thiết cho Yii2
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Cài đặt Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
