<?php

namespace backend\models;

use common\models\User;
use Yii;
use yii\bootstrap\Html;
use yii\web\HttpException;

/**
 * This is the model class for table "trong_tre_chi_luong".
 *
 * @property int $id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int $user_id
 * @property int $don_dich_vu_id
 * @property float|null $tong_tien
 * @property float|null $an_trua
 * @property float|null $thanh_tien
 * @property int $giao_vien_id
 * @property float|null $them_gio
 * @property float|null $don_gia
 * @property float|null $phu_phi_khac
 * @property int $buoi_hoc_id
 *
 * @property TienDoKhoaHoc $buoiHoc
 * @property DonDichVu $donDichVu
 * @property User $giaoVien
 * @property User $user
 */
class ChiLuong extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_chi_luong';
    }
    public $total_money;
    public $total_date;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'don_dich_vu_id', 'giao_vien_id', 'buoi_hoc_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['user_id', 'don_dich_vu_id', 'giao_vien_id', 'buoi_hoc_id'], 'required'],
            [['tong_tien', 'an_trua', 'thanh_tien', 'them_gio', 'don_gia'], 'number'],
            [['buoi_hoc_id'], 'exist', 'skipOnError' => true, 'targetClass' => TienDoKhoaHoc::className(), 'targetAttribute' => ['buoi_hoc_id' => 'id']],
            [['don_dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonDichVu::className(), 'targetAttribute' => ['don_dich_vu_id' => 'id']],
            [['giao_vien_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['giao_vien_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'don_dich_vu_id' => 'Don Dich Vu ID',
            'tong_tien' => 'Tong Tien',
            'an_trua' => 'An Trua',
            'thanh_tien' => 'Thanh Tien',
            'giao_vien_id' => 'Giao Vien ID',
            'them_gio' => 'Them Gio',
            'don_gia' => 'Don Gia',
            'buoi_hoc_id' => 'Buoi Hoc ID',
        ];
    }

    /**
     * Gets query for [[BuoiHoc]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBuoiHoc()
    {
        return $this->hasOne(TienDoKhoaHoc::className(), ['id' => 'buoi_hoc_id']);
    }

    /**
     * Gets query for [[DonDichVu]].
     *
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord
     */
    public function getDonDichVu()
    {
        return DonDichVu::find()->where(['id' => $this->don_dich_vu_id])->one();;
    }

    /**
     * Gets query for [[GiaoVien]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGiaoVien()
    {
        return $this->hasOne(User::className(), ['id' => 'giao_vien_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert){
            $giaoDich = new GiaoDich();
            $giaoDich->so_tien = $this->thanh_tien;
            $giaoDich->ghi_chu = "Cộng tiền Bid";
            $giaoDich->type = GiaoDich::NAP_TIEN;
            $giaoDich->user_id = $this->giao_vien_id;
            $giaoDich->tieu_de = "Cộng tiền cho đơn số";
            $giaoDich->don_dich_vu_id = $this->don_dich_vu_id;
            if (!$giaoDich->save()){
                throw new HttpException(500,Html::errorSummary($giaoDich));
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
