<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_chuong_trinh_hoc".
 *
 * @property int $id
 * @property int $active
 * @property string $created
 * @property string $updated
 * @property int $user_id
 * @property int|null $bat_chuong_trinh
 * @property string|null $tieu_de
 * @property int|null $dich_vu_id
 * @property string|null $image
 * @property string|null $goi_hoc
 *
 * @property DichVu $dichVu
 * @property User $user
 */
class ChuongTrinhHoc extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_chuong_trinh_hoc';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'bat_chuong_trinh', 'dich_vu_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['user_id'], 'required'],
            [['image'], 'string'],
            [['tieu_de'], 'string'],
            [['dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DichVu::className(), 'targetAttribute' => ['dich_vu_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'bat_chuong_trinh' => 'Bat Chuong Trinh',
            'tieu_de' => 'Tieu De',
            'dich_vu_id' => 'Dich Vu ID',
            'image' => 'Image',
        ];
    }

    /**
     * Gets query for [[DichVu]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDichVu()
    {
        return $this->hasOne(DichVu::className(), ['id' => 'dich_vu_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
