<?php

namespace backend\models;

use common\models\User;
use Yii;
use yii\bootstrap\Html;
use yii\helpers\VarDumper;
use yii\web\HttpException;

/**
 * This is the model class for table "{{%dich_vu}}".
 *
 * @property int $id
 * @property string|null $ten_dich_vu
 * @property string|null $image
 * @property string $created
 * @property string $updated
 * @property int $active
 * @property int $khoa_dich_vu
 * @property int|null $user_id
 * @property int|null $do_tuoi_id
 * @property int|null $loai_dich_vu_id
 * @property string|null $gia_tri
 * @property string|null $cam_ket
 * @property string|null $link
 * @property string|null $hop_dong_dich_vu
 *
 * @property DanhMuc $doTuoi
 * @property DanhMuc $loadDichVu
 * @property User $user
 */
class DichVu extends \yii\db\ActiveRecord
{
  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return '{{%dich_vu}}';
  }
  const CHAM_SOC_TRE= 165;
  const GIAO_DUC_SOM= 166;

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
      [['image', 'gia_tri', 'hop_dong_dich_vu'], 'string'],
      [['created', 'updated'], 'safe'],
      [['active', 'user_id', 'do_tuoi_id'], 'integer'],
      [['ten_dich_vu'], 'string'],
      [['do_tuoi_id'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['do_tuoi_id' => 'id']],
      [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
      [['loai_dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['loai_dich_vu_id' => 'id']],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'ten_dich_vu' => 'Ten Dich Vu',
      'image' => 'Image',
      'created' => 'Created',
      'updated' => 'Updated',
      'active' => 'Active',
      'user_id' => 'User ID',
      'do_tuoi_id' => 'Do Tuoi ID',
      'gia_tri' => 'Gia Tri',
      'cam_ket' => 'Cam Ket',
      'hop_dong_dich_vu' => 'Hop Dong Dich Vu',
    ];
  }

  /**
   * Gets query for [[DoTuoi]].
   *
   * @return \yii\db\ActiveQuery
   */
  public function getDoTuoi()
  {
    return $this->hasOne(DanhMuc::className(), ['id' => 'do_tuoi_id']);
  }

  public function getLoaiDichVu()
  {
    return $this->hasOne(DanhMuc::className(), ['id' => 'loai_dich_vu_id']);
  }

  /**
   * Gets query for [[User]].
   *
   * @return \yii\db\ActiveQuery
   */
  public function getUser()
  {
    return $this->hasOne(User::className(), ['id' => 'user_id']);
  }

  public function beforeSave($insert)
  {
    if ($insert) {
      $this->created = date('Y-m-d H:i:s');
    }
    $this->updated = date('Y-m-d H:i:s');

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function afterSave($insert, $changedAttributes)
  {
    if ($insert) {
      if ($this->loai_dich_vu_id == DichVu::CHAM_SOC_TRE){
        $this->updateFormChamSocTre();
      }
    }
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }

  public function updateFormChamSocTre()
  {
    $form = CauHinh::findOne(41);
      $data = [];

    $cauHois =json_decode($form->ghi_chu);
      DanhGiaBuoiHoc::deleteAll(['dich_vu_id'=>$this->id,'danh_muc_id'=>69]);
    foreach ($cauHois as $item) {
      $item = (object)$item;
      $cauHoi = new DanhGiaBuoiHoc();
      $cauHoi->dich_vu_id = $this->id;
      $cauHoi->muc_do =$item->muc_do!=""? json_encode($item->muc_do):null;
      $cauHoi->user_id = $this->user_id;
      $cauHoi->tieu_de = $item->tieu_de;
      $cauHoi->goi_y = json_encode($item->goi_y);
      $cauHoi->nhan_xet = $item->nhan_xet;
      $cauHoi->danh_muc_id = 69;
      $cauHoi->type = isset($item->type)?$item->type:0;
        $data[] = $cauHoi;
      if (!$cauHoi->save()) {
        throw new HttpException(500, Html::errorSummary($cauHoi));
      }else{
        if (isset($item->buoi)){
          $cauHoi->updateAttributes(['cac_buoi'=>json_encode($item->buoi)]);
          foreach ($item->buoi as $buoi){
            $mucDoBuoi = new DanhGiaBuoiHoc();
            $mucDoBuoi->tieu_de = $buoi;
            $mucDoBuoi->muc_do = json_encode($item->muc_do);
            $mucDoBuoi->parent_id = $cauHoi->id;
            $mucDoBuoi->danh_muc_id = 69;
            $mucDoBuoi->user_id = $this->user_id;
            $mucDoBuoi->dich_vu_id = $this->id;
            if (!$mucDoBuoi->save()) {
              throw new HttpException(500, Html::errorSummary($mucDoBuoi));
            }
          }
        }
      }
    }
  }
}
