<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%gia_dich_vu}}".
 *
 * @property int $id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $user_id
 * @property int|null $trinh_do
 * @property int|null $so_buoi
 * @property float|null $tong_tien
 * @property int|null $khuyen_mai
 * @property int|null $thanh_tien
 * @property int|null $dich_vu_id
 * @property int|null $khung_gio_id
 *
 * @property User $user
 * @property DichVu $dichVu
 * @property DanhMuc $trinhDo
 * @property KhungThoiGian $khungGio
 */
class GiaDichVu extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%gia_dich_vu}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'trinh_do', 'so_buoi', 'khuyen_mai', 'thanh_tien', 'dich_vu_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['tong_tien'], 'number'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DichVu::className(), 'targetAttribute' => ['dich_vu_id' => 'id']],
            [['trinh_do'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['trinh_do' => 'id']],
            [['khung_gio_id'], 'exist', 'skipOnError' => true, 'targetClass' => KhungThoiGian::className(), 'targetAttribute' => ['khung_gio_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'trinh_do' => 'Trinh Do',
            'so_buoi' => 'So Buoi',
            'tong_tien' => 'Tong Tien',
            'khuyen_mai' => 'Khuyen Mai',
            'thanh_tien' => 'Thanh Tien',
            'dich_vu_id' => 'Dich Vu ID',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[DichVu]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDichVu()
    {
        return $this->hasOne(DichVu::className(), ['id' => 'dich_vu_id']);
    }

    /**
     * Gets query for [[TrinhDo]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTrinhDo()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'trinh_do']);
    }
    public function getKhungGio()
    {
        return $this->hasOne(KhungThoiGian::className(), ['id' => 'khung_gio_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
