<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_gia_han_don".
 *
 * @property int $id
 * @property int|null $user_id
 * @property int $don_dich_vu_id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $so_buoi
 * @property int|null $tong_tien
 *
 * @property DonDichVu $donDichVu
 * @property User $user
 */
class GiaHanDon extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_gia_han_don';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'don_dich_vu_id', 'active', 'so_buoi'], 'integer'],
            [['don_dich_vu_id'], 'required'],
            [['created', 'updated'], 'safe'],
            [['don_dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonDichVu::className(), 'targetAttribute' => ['don_dich_vu_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'don_dich_vu_id' => 'Don Dich Vu ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'so_buoi' => 'So Buoi',
        ];
    }

    /**
     * Gets query for [[DonDichVu]].
     *
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord
     */
    public function getDonDichVu()
    {
        return DonDichVu::find()->where(['id' => $this->don_dich_vu_id])->one();;
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
  public function beforeSave($insert)
  {
    if ($insert){
      $this->created =date('Y-m-d H:i:s');
    }
    $this->updated =date('Y-m-d H:i:s');

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }
}
