<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_giao_cu".
 *
 * @property int $id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int $user_id
 * @property string|null $code
 * @property int|null $so_luong_tong
 * @property int|null $so_luong_hong
 * @property int|null $so_luong_ton
 * @property string|null $ghi_chu
 * @property string|null $image
 *
 * @property User $user
 */
class GiaoCu extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_giao_cu';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'so_luong_tong', 'so_luong_ton'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['user_id'], 'required'],
            [['ghi_chu', 'image'], 'string'],
            [['code'], 'string'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'code' => 'Code',
            'so_luong_tong' => 'So Luong Tong',
            'so_luong_ton' => 'So Luong Ton',
            'ghi_chu' => 'Ghi Chu',
            'image' => 'Image',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
