<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_hoa_don".
 *
 * @property int $id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $user_id
 * @property string|null $ho_ten
 * @property string|null $cmnd_cccd
 * @property string|null $dia_chi
 * @property string|null $ma_so_thue
 * @property string|null $email
 * @property string|null $ho_ten_con
 * @property int|null $nam_sinh_cua_con
 * @property int|null $don_dich_vu_id
 *
 * @property DonDichVu $donDichVu
 * @property User $user
 */
class HoaDon extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_hoa_don';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'nam_sinh_cua_con', 'don_dich_vu_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['dia_chi'], 'string'],
            [['ho_ten', 'email', 'ho_ten_con'], 'string'],
            [['cmnd_cccd', 'ma_so_thue'], 'string', 'max' => 20],
            [['don_dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonDichVu::className(), 'targetAttribute' => ['don_dich_vu_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'ho_ten' => 'Ho Ten',
            'cmnd_cccd' => 'Cmnd Cccd',
            'dia_chi' => 'Dia Chi',
            'ma_so_thue' => 'Ma So Thue',
            'email' => 'Email',
            'ho_ten_con' => 'Ho Ten Con',
            'nam_sinh_cua_con' => 'Nam Sinh Cua Con',
            'don_dich_vu_id' => 'Don Dich Vu ID',
        ];
    }

    /**
     * Gets query for [[DonDichVu]].
     *
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord
     */
    public function getDonDichVu()
    {
        return DonDichVu::find()->where(['id' => $this->don_dich_vu_id])->one();;
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
