<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_hoan_thanh_dao_tao".
 *
 * @property int $id
 * @property int|null $active
 * @property int $user_id
 * @property string|null $updated
 * @property string|null $created
 * @property int|null $giao_vien_id
 * @property int|null $hoc_phan_id
 * @property int|null $tong_bai_hoc
 * @property int|null $tong_bai_da_hoan_thanh
 * @property string|null $trang_thai
 *
 * @property User $giaoVien
 * @property HocPhan $hocPhan
 * @property User $user
 */
class HoanThanhDaoTao extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_hoan_thanh_dao_tao';
    }
    const CHUA_HOAN_THANH = 'Chưa hoàn thành';
    const DA_HOAN_THANH = 'Đã hoàn thành';
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'giao_vien_id', 'hoc_phan_id', 'tong_bai_hoc', 'tong_bai_da_hoan_thanh'], 'integer'],
            [['user_id'], 'required'],
            [['updated', 'created'], 'safe'],
            [['trang_thai'], 'string'],
            [['giao_vien_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['giao_vien_id' => 'id']],
            [['hoc_phan_id'], 'exist', 'skipOnError' => true, 'targetClass' => HocPhan::className(), 'targetAttribute' => ['hoc_phan_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'user_id' => 'User ID',
            'updated' => 'Updated',
            'created' => 'Created',
            'giao_vien_id' => 'Giao Vien ID',
            'hoc_phan_id' => 'Hoc Phan ID',
            'tong_bai_hoc' => 'Tong Bai Hoc',
            'tong_bai_da_hoan_thanh' => 'Tong Bai Da Hoan Thanh',
            'trang_thai' => 'Trang Thai',
        ];
    }

    /**
     * Gets query for [[GiaoVien]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGiaoVien()
    {
        return $this->hasOne(User::className(), ['id' => 'giao_vien_id']);
    }

    /**
     * Gets query for [[HocPhan]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getHocPhan()
    {
        return $this->hasOne(HocPhan::className(), ['id' => 'hoc_phan_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
