<?php

namespace backend\models;

use common\models\User;

/**
 * This is the model class for table "{{%khieu_nai}}".
 *
 * @property int $id
 * @property int $user_id
 * @property string|null $noi_dung
 * @property string|null $phan_hoi
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property string|null $tinh_trang
 *
 * @property User $user
 */
class KhieuNai extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%khieu_nai}}';
    }

    const CHUA_XU_LY = "Chưa xử lý";
    const DA_XU_LY = "Đã xử lý";

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id', 'active'], 'integer'],
            [['noi_dung', 'phan_hoi'], 'string'],
            [['created', 'updated'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'noi_dung' => 'Noi Dung',
            'phan_hoi' => 'Phan Hoi',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
            $this->tinh_trang = self::CHUA_XU_LY;
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
