<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "trong_tre_khoa_hoc".
 *
 * @property int $id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $type
 * @property string|null $updated
 * @property int|null $user_id
 * @property int|null $dich_vu_id
 * @property string|null $image
 * @property string|null $tieu_de
 * @property string|null $ghi_chu
 *
 * @property HocPhan[] $hocPhans
 * @property KetQuaDaoTao[] $ketQuaDaoTaos
 * @property DichVu $dichVu
 */
class KhoaHoc extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_khoa_hoc';
    }
    const GIAO_VIEN = 'Giáo viên';
    const TRE_EM = 'Trẻ em';
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['image', 'ghi_chu'], 'string'],
            [['tieu_de'], 'string'],
            [['dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DichVu::className(), 'targetAttribute' => ['dich_vu_id' => 'id']],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'image' => 'Image',
            'tieu_de' => 'Tieu De',
            'ghi_chu' => 'Ghi Chu',
            'dich_vu_id' => 'Dịch vu',
        ];
    }

    /**
     * Gets query for [[HocPhans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getHocPhans()
    {
        return $this->hasMany(HocPhan::className(), ['khoa_hoc_id' => 'id']);
    }
    public function getDichVu()
    {
        return $this->hasOne(DichVu::className(), ['id' => 'dich_vu_id']);
    }

    /**
     * Gets query for [[KetQuaDaoTaos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKetQuaDaoTaos()
    {
        return $this->hasMany(KetQuaDaoTao::className(), ['khoa_hoc_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
