<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_khung_thoi_gian".
 *
 * @property int $id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $user_id
 * @property int|null $type
 * @property int|null $khung_gio
 * @property string|null $noi_dung
 * @property int|null $dich_vu_id
 * @property int|null $so_gio
 *
 * @property DichVu $dichVu
 * @property DanhMuc $khungGio
 * @property User $user
 * @property DanhMuc $khungGio0
 * @property DanhMuc $type0
 */
class KhungThoiGian extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_khung_thoi_gian';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'type', 'khung_gio', 'dich_vu_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['noi_dung'], 'string'],
            [['dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DichVu::className(), 'targetAttribute' => ['dich_vu_id' => 'id']],
            [['khung_gio'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['khung_gio' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['khung_gio'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['khung_gio' => 'id']],
            [['type'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['type' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'type' => 'Type',
            'khung_gio' => 'Khung Gio',
            'noi_dung' => 'Noi Dung',
            'dich_vu_id' => 'Dich Vu ID',
        ];
    }

    /**
     * Gets query for [[DichVu]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDichVu()
    {
        return $this->hasOne(DichVu::className(), ['id' => 'dich_vu_id']);
    }

    /**
     * Gets query for [[KhungGio]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKhungGio()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'khung_gio']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[KhungGio0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKhungGio0()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'khung_gio']);
    }

    /**
     * Gets query for [[Type0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getType0()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'type']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
