<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_lich_su_trang_thai_thanh_toan".
 *
 * @property int $id
 * @property int|null $don_hang_id
 * @property string|null $trang_thai
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $hinh_thuc_thanh_toan_id
 * @property string|null $ghi_chu
 * @property int|null $active
 * @property int|null $user_id
 * @property float|null $tong_tien

 * @property DonDichVu $donHang
 * @property DanhMuc $hinhThucThanhToan
 * @property User $user
 */
class LichSuTrangThaiThanhToan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_lich_su_trang_thai_thanh_toan';
    }
    const CHUA_THANH_TOAN = 'Chưa thanh toán';
    const DA_THANH_TOAN = 'Đã thanh toán';
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['don_hang_id', 'hinh_thuc_thanh_toan_id', 'active', 'user_id'], 'integer'],
            [['trang_thai', 'ghi_chu'], 'string'],
            [['created', 'updated','tong_tien'], 'safe'],
            [['don_hang_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonDichVu::className(), 'targetAttribute' => ['don_hang_id' => 'id']],
            [['hinh_thuc_thanh_toan_id'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['hinh_thuc_thanh_toan_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'don_hang_id' => 'Don Hang ID',
            'trang_thai' => 'Trang Thai',
            'created' => 'Created',
            'updated' => 'Updated',
            'hinh_thuc_thanh_toan_id' => 'Hinh Thuc Thanh Toan ID',
            'ghi_chu' => 'Ghi Chu',
            'active' => 'Active',
            'user_id' => 'User ID',
        ];
    }

    /**
     * Gets query for [[DonHang]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDonHang()
    {
        return $this->hasOne(DonDichVu::className(), ['id' => 'don_hang_id']);
    }

    /**
     * Gets query for [[HinhThucThanhToan]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getHinhThucThanhToan()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'hinh_thuc_thanh_toan_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
