<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_lich_su_viec_lam_giao_vien".
 *
 * @property int $id
 * @property int $active
 * @property string|null $created
 * @property string|null $updated
 * @property string|null $trang_thai
 * @property int $user_id
 * @property int $don_dich_vu_id
 * @property int|null $tong_buoi
 * @property int|null $so_buoi
 * @property float|null $don_gia
 * @property int $giao_vien_id
 *
 * @property DonDichVu $donDichVu
 * @property User $giaoVien
 * @property User $user
 */
class LichSuViecLamGiaoVien extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_lich_su_viec_lam_giao_vien';
    }
    const DA_HOAN_THANH= "Đã hoàn thành";
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'don_dich_vu_id', 'tong_buoi', 'so_buoi', 'giao_vien_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['user_id', 'don_dich_vu_id', 'giao_vien_id'], 'required'],
            [['don_gia'], 'number'],
            [['don_dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonDichVu::className(), 'targetAttribute' => ['don_dich_vu_id' => 'id']],
            [['giao_vien_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['giao_vien_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'don_dich_vu_id' => 'Don Dich Vu ID',
            'tong_buoi' => 'Tong Buoi',
            'so_buoi' => 'So Buoi',
            'don_gia' => 'Don Gia',
            'giao_vien_id' => 'Giao Vien ID',
        ];
    }

    /**
     * Gets query for [[DonDichVu]].
     *
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord
     */
    public function getDonDichVu()
    {
        return DonDichVu::find()->where(['id' => $this->don_dich_vu_id])->one();;
    }

    /**
     * Gets query for [[GiaoVien]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGiaoVien()
    {
        return $this->hasOne(User::className(), ['id' => 'giao_vien_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
