<?php

namespace backend\models;

use common\models\User;
use yii\bootstrap\Html;

/**
 * This is the model class for table "trong_tre_nhan_lich".
 *
 * @property int $id
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $user_id
 * @property int|null $giao_vien_id
 * @property int|null $don_dich_vu_id
 * @property string|null $trang_thai
 * @property string|null $ghi_chu
 * @property string|null $form_danh_gia
 *
 * @property LichSuTrangThaiNhanLich[] $lichSuTrangThaiNhanLiches
 * @property DonDichVu $donDichVu
 * @property User $giaoVien
 * @property User $user
 */
class NhanLich extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_nhan_lich';
    }

    const CHUA_NHAN = 'Chưa nhận';
    const DANG_CHO_DUYET = 'Đang chờ duyệt';
    const DA_DUYET = 'Đã duyệt';
    const DANG_DAY = 'Đang dạy';
    const DA_HUY = 'Đã hủy';
    const DA_HOAN_THANH = 'Đã hoàn thành';

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'user_id', 'giao_vien_id', 'don_dich_vu_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['trang_thai', 'ghi_chu'], 'string'],
            [['don_dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonDichVu::className(), 'targetAttribute' => ['don_dich_vu_id' => 'id']],
            [['giao_vien_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['giao_vien_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'giao_vien_id' => 'Giao Vien ID',
            'don_dich_vu_id' => 'Don Dich Vu ID',
            'trang_thai' => 'Trang Thai',
            'ghi_chu' => 'Ghi Chu',
        ];
    }

    /**
     * Gets query for [[LichSuTrangThaiNhanLiches]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLichSuTrangThaiNhanLiches()
    {
        return $this->hasMany(LichSuTrangThaiNhanLich::className(), ['nhan_lich_id' => 'id']);
    }

    /**
     * Gets query for [[DonDichVu]].
     *
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord
     */
    public function getDonDichVu()
    {
        return DonDichVu::find()->where(['id' => $this->don_dich_vu_id])->one();;
    }

    /**
     * Gets query for [[GiaoVien]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGiaoVien()
    {
        return $this->hasOne(User::className(), ['id' => 'giao_vien_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created = date('Y-m-d H:i:s');
        }
        $this->updated = date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($this->trang_thai != "") {
            $trangThai = new LichSuTrangThaiNhanLich();
            $trangThai->nhan_lich_id = $this->id;
            $trangThai->trang_thai = $this->trang_thai;
            $trangThai->user_id = $this->user_id;
            $trangThai->ghi_chu = $this->ghi_chu;
            if (!$trangThai->save()) {
                throw new \yii\web\HttpException(500, Html::errorSummary($trangThai));
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getTrangThaiID()
    {
        $arr = [
            self::CHUA_NHAN => 82,
            self::DANG_CHO_DUYET => 83,
            self::DA_DUYET => 84,
            self::DANG_DAY => 85,
            self::DA_HUY => 86,
            self::DA_HOAN_THANH => 87,
        ];
        return [
            'id' => isset($arr[$this->trang_thai]) ? $arr[$this->trang_thai] : 82,
            'name' => $this->trang_thai
        ];
    }
}
