<?php

namespace backend\models;

use common\models\User;
use Yii;
use yii\bootstrap\Html;
use yii\web\HttpException;

/**
 * This is the model class for table "trong_tre_phu_phi".
 *
 * @property int $id
 * @property float|null $tong_tien
 * @property string|null $ghi_chu
 * @property int|null $active
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $user_id
 * @property string|null $tieu_de
 * @property int $type_id
 * @property int|null $don_dich_vu_id
 *
 * @property DanhMuc $type
 * @property User $user
 * @property DonDichVu $donDichVu
 */
class PhuPhi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_phu_phi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tong_tien'], 'number'],
            [['ghi_chu'], 'string'],
            [['active', 'user_id', 'type_id', 'don_dich_vu_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['type_id'], 'required'],
            [['tieu_de'], 'string'],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['type_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['don_dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonDichVu::className(), 'targetAttribute' => ['don_dich_vu_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tong_tien' => 'Tong Tien',
            'ghi_chu' => 'Ghi Chu',
            'active' => 'Active',
            'created' => 'Created',
            'updated' => 'Updated',
            'user_id' => 'User ID',
            'tieu_de' => 'Tieu De',
            'type_id' => 'Type ID',
            'don_dich_vu_id' => 'Don Dich Vu ID',
        ];
    }

    /**
     * Gets query for [[Type]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'type_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[DonDichVu]].
     *
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord
     */
    public function getDonDichVu()
    {
        return DonDichVu::find()->where(['id' => $this->don_dich_vu_id])->one();;
    }
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created = date('Y-m-d H:i:s');
        }
        $this->updated = date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
