<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%quyen_loi}}".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $created
 * @property string|null $updated
 * @property int|null $active
 * @property int|null $dich_vu_id
 * @property string|null $name
 * @property string|null $link
 *
 * @property DichVu $dichVu
 * @property User $user
 */
class QuyenLoi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%quyen_loi}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'active', 'dich_vu_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['link'], 'string'],
            [['name'], 'string'],
            [['dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => DichVu::className(), 'targetAttribute' => ['dich_vu_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'created' => 'Created',
            'updated' => 'Updated',
            'active' => 'Active',
            'dich_vu_id' => 'Dich Vu ID',
            'name' => 'Name',
            'link' => 'Link',
        ];
    }

    /**
     * Gets query for [[DichVu]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDichVu()
    {
        return $this->hasOne(DichVu::className(), ['id' => 'dich_vu_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
