<?php

namespace backend\models;

use backend\models\DanhMuc;
use common\models\User;
use Yii;

/**
 * This is the model class for table "trong_tre_tin_tuc".
 *
 * @property int $id
 * @property string|null $tieu_de
 * @property string|null $noi_dung
 * @property string|null $anh_dai_dien
 * @property string|null $created
 * @property int $user_id
 * @property string|null $updated
 * @property int|null $type
 * @property int $active
 * @property string|null $link
 * @property int|null $status
 *
 * @property DanhMuc $type0
 * @property User $user
 */
class TinTuc extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trong_tre_tin_tuc';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['noi_dung', 'anh_dai_dien', 'link'], 'string'],
            [['created', 'updated'], 'safe'],
            [['user_id'], 'required'],
            [['user_id', 'type', 'active', 'status'], 'integer'],
            [['tieu_de'], 'string'],
            [['type'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['type' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tieu_de' => 'Tieu De',
            'noi_dung' => 'Noi Dung',
            'anh_dai_dien' => 'Anh Dai Dien',
            'created' => 'Created',
            'user_id' => 'User ID',
            'updated' => 'Updated',
            'type' => 'Type',
            'active' => 'Active',
            'link' => 'Link',
            'status' => 'Status',
        ];
    }

    /**
     * Gets query for [[Type0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getType0()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'type']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if ($insert){
            $this->created =date('Y-m-d H:i:s');
        }
        $this->updated =date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
