version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8001:8080"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mynetwork
  php:
    build: ./php
    container_name: php
    ports:
      - "8002:8080"
    volumes:
      - ./src:/var/www/html
    networks:
      - mynetwork
    working_dir: /var/www/html

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: myUser
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8003:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  dbdata:

networks:
  mynetwork:
