<?php

namespace backend\controllers;

use common\models\User;
use yii\helpers\VarDumper;
use yii\web\Controller;

class CoreController extends Controller
{
    public function beforeAction($action)
    {
//        VarDumper::dump($action->id);exit();
        if(!in_array($action->id, [
            'login',
            'logout',
            'error',
            'get-form-giao-vien',
            'get-form-phu-huynh',
            'save-khao-sat'
        ])) {
            if(!\Yii::$app->user->isGuest){
                $user = User::findOne(\Yii::$app->user->id);
                if($user->status == 0)
                    $this->redirect(\yii\helpers\Url::toRoute('site/logout'));
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
