<?php
/**
 * Created by PhpStorm.
 * User: pnevn
 * Date: 2/22/2019
 * Time: 5:00 PM
 */
namespace common\models;
use backend\models\LogIS;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\helpers\Html;
use yii\helpers\VarDumper;
class myActiveRecord extends ActiveRecord
{
    public function beforeSave($insert)
    {
//        if(in_array('code', self::attributes()) && in_array('name', self::attributes())){
//            $this->name = trim($this->name);
//            $this->code = myAPI::createCode(self::getAttribute("name"));
//        }
//        if(in_array('created', self::attributes())){
//            if($insert){
//                $this->created = date("Y-m-d H:i:s");
//            }else{
//                if(in_array('updated', self::attributes()))
//                    $this->updated = date("Y-m-d H:i:s");
//            }
//        }
//        if(in_array('user_id', self::attributes())){
//            if($insert){
//                $this->user_id = \Yii::$app->user->id;
//            }
//        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
//        $log = new LogIS();
//        if($insert)
//            $log->created = date("Y-m-d H:i:s");
//        else
//            $log->updated = date("Y-m-d H:i:s");
//        $log->user_id = \Yii::$app->user->id;
//        $log->id_column = self::getAttribute('id');
//        $table = str_replace('{', '', self::tableName());
//        $table = str_replace('}', '', $table);
//        if(strpos($table, '%') >=0)
//            $table = "is_".$table;
//        $table = str_replace('%', '', $table);
//        $log->type = trim($table);
//        if(!$log->save())
//            VarDumper::dump(\yii\bootstrap\Html::errorSummary($log), 10, true);
//        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
    public function afterDelete()
    {
//        $log = new LogIS();
//        $log->deleted = date("Y-m-d H:i:s");
//        $log->user_id = \Yii::$app->user->id;
//        $log->id_column = self::getAttribute('id');
//        $table = str_replace('{', '', self::tableName());
//        $table = str_replace('}', '', $table);
//        if(strpos($table, '%') >=0)
//            $table = "is_".$table;
//        $table = str_replace('%', '', $table);
//        $log->type = trim($table);
//        if(!$log->save())
//            VarDumper::dump(\yii\bootstrap\Html::errorSummary($log), 10, true);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
